### ISSUE TITLE
How to get ICD10PCS codes either from procedure concept or IDs?

### ISSUE THREAD

**Issue by Raghu17s** [yubin-park/hcuppy#2]
Hi Folks,

Is it possible to get ICD-10-PCS codes either using procedure concept name, concept ID, or concept code using hcuppy?

**Comment by yubin-park** [comment]
Currently, the package does not support the reverse mapping. However, you
can use

```
from hcuppy.ccs import CCSEngine
ccse = CCSEngine("pr")
ccse.x2ccs # this is a dictionary that contains the procedure to CCS
mapping. You can use this to make the reverse mapping
```
