### ISSUE TITLE
get_elixhauser() does not work as described in example

### ISSUE THREAD

**Issue by JBarsotti** [yubin-park/hcuppy#7]
Hi,

First off, I love this module so, so much!

Just a small thing I've found is that the get_elixhauser() function does not work as described in the example. I keep getting an error saying that the function only takes 2 inputs, but 3 are given. I looked at your code and it does seem to be correct, so maybe I'm using an older version? I installed the package using "pip install hcuppy."

Thank you so much for all your hard work!

**Comment by fjbriones** [comment]
I think installing using pip will result into an older version of hcuppy. It's best to install using sourc for now or just give a diagnosis list without indicating poa or full list.

**Comment by thepvtimes** [comment]
I believe there might be issues with the readmit & mortality score. I just ran 10k+ examples and did not have one mortality score that was not 0. Then i ran a few tests with the same diagnosis codes from the example and only the comorbidities matched the output.

**Comment by yubin-park** [comment]
@JBarsotti  sorry for getting back so late. As @fjbriones said, yes, the PIP version is outdated. We will update the PIP version in a couple of weeks.
@thepvtimes could you provide some examples (deanonymized). I will for sure take a look soon!

**Comment by thepvtimes** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/pvandenb/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/pvandenb/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



['A4189', 'G9341',   'I2699', 'I5021', 'U071'] | ['G9341', 'I2699', 'I5021', 'U071'] | {'cmrbdt_lst': ['NEURO_OTH', 'HF'],   'rdmsn_scr': 0, 'mrtlt_scr': 0}
-- | -- | --
['K56609'] | ['K56609'] | {'cmrbdt_lst': [], 'rdmsn_scr': 0, 'mrtlt_scr': 0}
['J1289', 'J159', 'J9601', 'U071'] | ['J1289', 'J159', 'J9601', 'U071'] | {'cmrbdt_lst': [], 'rdmsn_scr': 0, 'mrtlt_scr': 0}
['J45901', 'J9601', 'N179', 'Z6843'] | ['J9601', 'N179'] | {'cmrbdt_lst': ['LUNG_CHRONIC', 'OBESE'], 'rdmsn_scr': -3, 'mrtlt_scr':   0}
['I442', 'N179'] | ['I442', 'N179'] | {'cmrbdt_lst': [], 'rdmsn_scr': 0, 'mrtlt_scr': 0}
['G8194', 'I609', 'I63519', 'T80818A'] | ['G8194', 'I609', 'I63519'] | {'cmrbdt_lst': ['PARALYSIS', 'CBVD_POA', 'CBVD'], 'rdmsn_scr': 0,   'mrtlt_scr': 0}



</body>

</html>
![image](https://user-images.githubusercontent.com/127004479/223804241-b71fcb91-b067-4fdd-952c-4aebbe57e7aa.png)

Attached is a small sample of my output where the Comorbidity list populates but the Readmit score seems to worked in a limited fashion and the mortality score not at all. The image mirrors the diagnosis codes from the example provided on how to use the software where the scores are as follows:   "rdmsn_scr": 31, "mrtlt_scr": 9

**Comment by thepvtimes** [comment]
I ran this code from your example process ;

>>> from hcuppy.elixhauser import ElixhauserEngine
>>> ee = ElixhauserEngine()
>>> dx_full_lst = ["E640", "E119", "B190"]
>>> dx_poa_lst = ["E119", "B190"]
>>> out = ee.get_elixhauser(dx_full_lst, dx_poa_lst)
>>> print(out)
{'cmrbdt_lst': ['WGHTLOSS', 'DIAB_UNCX', 'LIVER_SEV'],
 'mrtlt_scr': 31,
 'rdmsn_scr': 16}
>>>

And my result was;

{'cmrbdt_lst': ['WGHTLOSS', 'DIAB_UNCX', 'LIVER_SEV'], 'rdmsn_scr': 10, 'mrtlt_scr': 0}

I also ran the aforementioned 10k+ examples where there are no mortality scores reported across the entire dataset and what seem to be diminished Readmit scores.

**Comment by thepvtimes** [comment]
> @JBarsotti sorry for getting back so late. As @fjbriones said, yes, the PIP version is outdated. We will update the PIP version in a couple of weeks. @thepvtimes could you provide some examples (deanonymized). I will for sure take a look soon!

Curious if you've had a chance to ammend the code yet? Thanks.

**Comment by ch-nickgustafson** [comment]
@thepvtimes I came across this package and at a quick glance, there appear to be a few issues with the `Elixhauser` class. 

1. The mortality weights all have a prefix of `mw`, while it looks like the python based code doesn't expect this ([Example](https://github.com/yubin-park/hcuppy/blob/3fc6897/hcuppy/elixhauser.py#L50-L87))
2. Even with the `mw` prefix removed, there are also several mismatches between the keys uses for the `rdmsn` dictionary and those used for the `mrtlt` when comparing to the SAS file referenced in the comment ([Link to SAS implementation](https://github.com/yubin-park/hcuppy/blob/3fc6897/hcuppy/data/CMR_Index_Program_v2023-1.sas#L82)).
3. I also noticed that the unit tests are failing for the `elixhauser` module. I haven't done much investigation, but at least the first 2 issues I outlined above explain some of the failure. There were also test failures for other modules, but I didn't look into those.

**Comment by yubin-park** [comment]
@thepvtimes @ch-nickgustafson 
Thanks so much for providing the detailed examples and pointers. Also, sorry for getting back so late.

I just pushed a new master branch, fixing the issues you guys listed. Please check it out if you have time. I added the `mw` and `rw` prefix to the condition names appropriately for the model, so that the scores are calculated. Now the unit tests should run fine as well as the README examples.

I also updated the newest branch to PIP https://test.pypi.org/project/hcuppy/0.0.8/

Thanks!
